#!/bin/bash

CACHE_DIR="${HOME}/.cache/myapp"
mkdir -p "${CACHE_DIR}"
pushd "${CACHE_DIR}"
for i in /usr/lib/myapp/* ; do
	basename="$(basename ${i})"
	if [ ! -f "${basename}" -a ! -L "${basename}" ]; then
		ln -s "${i}" . 2>/dev/null
	fi
done
java -jar /usr/lib/myapp/getdown.jar . 